#!/usr/bin/python
import sys

try: f = open(sys.argv[1])
except:
    print "Need to specify a file"
    quit()
code = f.read()
f.close()
global tape
tape = [0 for i in xrange(30000)]
global cur_cell
cur_cell = 0
counter = 0
global output
output = []


def control_head(char):
    global cur_cell
    global tape
    if char == "+": tape[cur_cell] += 1
    elif char == "-": tape[cur_cell] -= 1
    elif char == ">": cur_cell += 1
    elif char == "<": cur_cell -= 1
    elif char == ".": output.append(chr(tape[cur_cell]))
    else: return False

while counter != len(code):
    if code[counter] == "[": hold_place = counter

    if code[counter] == "]":
        if tape[cur_cell] != 0: counter = hold_place

    control_head(code[counter])

    counter += 1

print ''.join(output)
